# Usar la imagen base de Python 3.10
FROM python:3.10

# Crear una carpeta /app y establecerla como el entorno de trabajo
WORKDIR /app

# Añadir el fichero Python creado previamente
COPY Ej_1.py .

# Cuando se ejecute la imagen debe ejecutar nuestro fichero Python
CMD ["python", "./Ej_1.py"]
